### ISSUE TITLE
Plugin Scaffolding Automation

### ISSUE THREAD

**Issue by michealengland** [WebDevStudios/wds-block-starter#24]
Similar to https://www.npmjs.com/package/@wordpress/create-block, it would incredibly helpful is users did not have to manually scaffold the WDS Block Starter plugin when starting a new project.

## Guidelines
- It should be easy to get a new plugin spun up
- I would prefer that this does not require WP CLI and instead can be used directly from the terminal
- Users should be able to provide details in the terminal that help fillout the necessary changes for the plugin

**Comment by donmhico** [comment]
**Update**

The first version of the scaffolding command is now available:
https://github.com/WebDevStudios/create-block
https://www.npmjs.com/package/@webdevstudios/create-block

You can scaffold a block using the command
`npm init @webdevstudios/block WebDevStudios/SampleBlock`

At the moment, i'm re-creating the scaffolding package from scratch. I had a discussion with @salcode and @michealengland that the current way that the scaffolding package fetches the actual Block Starter files from this repo isn't ideal. This is because the current scaffolding package has the Block Starter files as templates, so when the WDS Block Starter files updates, the scaffolding package also needs to be updated.

The ideal solution is to have the scaffolding package fetch the WDS Block Starter files from this repo on-demand. I'm currently in the process of creating this. I'll provide updates as soon as possible.

**Comment by gregrickaby** [comment]
This can be closed. Check out our block starter with:

`npx @webdevstudios/block YourName/YourBlock`
