### ISSUE TITLE
Bootstrap a multi-block plugin structure

### ISSUE THREAD

**Issue by lmartins** [WebDevStudios/wds-block-starter#34]
Looks like this tool only supports a one block per plugin workflow, which is likely just fine for many use cases, but maybe falls apart for larger projects where you need to create multiple projects. I wonder if you have considered the option of having multiple blocks under the same plugin.

**Comment by michealengland** [comment]
@lmartins Thanks for opening the issue. I discussed this with @donmhico and at this time we're not pursuing a multi-block setup due to some of the complications that will occur with WP Scripts.

Some of the main challenges are:
- Extracting blocks into individual JS files which would require a large reconfiguration of the Webpack config
- Changing to a multiple file setup would also add some new challenges with the PostCSS config

As an alternative, we may add some adjustments in the future around how we import our block assets so that they're not tied to a block namespace.

In the meantime, you can add as many blocks as you'd like by importing adjusting the import structure under `/src`.
Example `/src`
```js
import './block-1';
import './block-2';
import './block-3';
```

**Comment by lmartins** [comment]
Thanks so much for the feedback and suggestion @michealengland  I'll proceed as suggested. Thank you!
